### ISSUE TITLE
content pages should be highlighted per media type

### ISSUE THREAD

**Issue by chadwhitacre** [AspenWeb/simplate.vim#3]
[Rendered simplates](http://aspen.io/simplates/rendered/) have one content page (the last page). It should be syntax highlighted according to the filename extension.

[Negotiated simplates](http://aspen.io/simplates/negotiated/) have multiple content pages. They should each be syntax highlighted according to the media type on the specline.

I wonder if the best way to do this isn't to somehow import aspen from within Vim and use aspen as a library to determine the media type per page.

**Comment by pjz** [comment]
Syntax hilighting per content-type is fixed as of 3aa3e44398d375bfc3444f2510c0ea0cd773edbb.   Syntax hilighting per templating language is still needed. (Note: should be okay using the 'contained' keyword, the syntax hilights can overlap.)

**Comment by chadwhitacre** [comment]
@pjz Awesome! Confirmed working. :-)

We actually have a separate ticket already for highlighting per renderer (#9), so I'm closing here.
