### ISSUE TITLE
Caret-L string sequence should be acceptable for separating pages

### ISSUE THREAD

**Issue by patcoll** [AspenWeb/simplate.vim#4]
There is the literal page break control character and then there is "^L" -- both should be supported for separating pages.

**Comment by chadwhitacre** [comment]
Obsolete now that we've switched Aspen in https://github.com/gittip/aspen-python/pull/171 to use `[---]` instead of `^L`.

**Comment by pjz** [comment]
This has been changed to be `[----*]` in sync with the latest aspen.

**Comment by chadwhitacre** [comment]
:-)
