### ISSUE TITLE
What is it supposed to do?

### ISSUE THREAD

**Issue by zbynekwinkler** [AspenWeb/simplate.vim#6]
I don't follow. Was the intention to create .spt file type that properly highlights the all the sections in the simplate? If not, can we make it so? :smiley:

**Comment by chadwhitacre** [comment]
Yes, the purpose is to highlight and indent all sections of a simplate file according to the proper rules. What are the proper rules? Consider this example simplate:

```
import random
[----] python
foo = "bar"
[----] text/html via pystache
Greetings, program!
```

 The first and second sections should be highlighted/indented as Python. The `Greetings, program!` block should be highlighted/indented according to the rules for both HTML and Pystache.

**Comment by chadwhitacre** [comment]
Closing this in favor of more specific tickets.
